name: at_talk
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependency_overrides:
#  at_client:
#    path: ../at_client_sdk/at_client
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: at_client
      ref: trunk

dependencies:
  at_client: ^3.0.30
  at_onboarding_cli: ^1.0.0
  chalkdart: ^2.0.8

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
