name: at_talk
description: A sample command-line application.
version: 1.1.0

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  at_client: ^3.0.68
  at_onboarding_cli: ^1.4.0
  at_utils: ^3.0.15
  chalkdart: ^2.0.9
  version: ^3.0.2
  args: ^2.4.2
  logging: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
