name: at_talk
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  at_client: ^3.0.56
  at_onboarding_cli: ^1.2.3
  chalkdart: ^2.0.8

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependency_overrides:
  at_onboarding_cli:
    path: ../at_libraries/packages/at_onboarding_cli
  at_client:
    path: ../at_client_sdk/packages/at_client
