name: at_talk
description: A sample command-line application.
version: 1.1.0

environment:
  sdk: '>=2.17.3 <4.0.0'

dependencies:
  at_client: ^3.0.58
  at_onboarding_cli: ^1.2.5
  chalkdart: ^2.0.9
  version: ^3.0.2

dependency_overrides:
  at_onboarding_cli:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_onboarding_cli
      ref: dart-3
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: packages/at_client
      ref: dart-3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
