name: at_talk
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  at_client: ^3.0.56
  at_onboarding_cli: ^1.2.3
  chalkdart: ^2.0.8
  dart_periphery: ^0.9.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependency_overrides:
  at_chops:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_chops
      ref: integrate_pkam_secure_element
  at_onboarding_cli:
#    path: ../at_libraries/packages/at_onboarding_cli
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_onboarding_cli
      ref: integrate_pkam_secure_element
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_lookup
      ref: integrate_pkam_secure_element
