name: at_talk
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  at_client: ^3.0.30
  at_onboarding_cli: ^1.0.0
  chalkdart: ^2.0.8

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
